services:
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        public: true

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    TriforceRbacBundle\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Exception/'
            - '../src/Repository/'

    TriforceRbacBundle\EventSubscriber\AccessControlDriver:
      tags:
        - { name: kernel.event_listener, event: onKernelController }

    TriforceRbacBundle\Repository\PermissionRepository:
        arguments:
            $entityClass: '%triforce_rbac.resolve_target_entities.permission%'

    TriforceRbacBundle\Repository\RoleRepository:
        arguments:
            $entityClass: '%triforce_rbac.resolve_target_entities.role%'
